GET http://localhost:8000/subscribers

###
GET http://localhost:8000/subscribers/5e6de8cf7d07ea09787da84e

###
POST http://localhost:8000/subscribers
Content-Type: application/json

{
    "name" : "Great person",
    "subscribedToChannel": "Web dev Simplified"
}

###

DELETE http://localhost:8000/subscribers/5e6de8cf7d07ea09787da84f
###

PATCH  http://localhost:8000/subscribers/5e6df101133925192c27b485
Content-Type: application/json

{
    "name" : "New name"
}


### Box art
GET http://localhost:8000/box_arts/Genesis/moratl-kombat